pipeline {
    agent any
    
    environment {
        DOCKER_HUB_CREDENTIALS = 'surya_docker'
        DOCKER_IMAGE_NAME = 'surya2126/to-do'
        DOCKER_CONTAINER_NAME = 'TO-DO-APP'
        DOCKER_IMAGE_TAG = "latest-${env.BUILD_NUMBER}"
        GIT_URL = 'https://github.com/dhanush2126/to-do-app.git'
    }
    
    stages {
         stage('cloning git url') {
            steps {
                git url: "${GIT_URL}"
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                        sh "pwd"
                        sh "cd ${WORKSPACE}/app"
                        sh "pwd"
                    docker.withRegistry('https://index.docker.io/v1/', DOCKER_HUB_CREDENTIALS) {
                        sh "docker build -t ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG} ${WORKSPACE}/app"
                    }
                }
            }
        }
        
        stage('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', DOCKER_HUB_CREDENTIALS) {
                        sh "docker push ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}"
                    }
                }
            }
        }
        stage('Clean Up Local Image') {
            steps {
                script {
                    sh "docker rmi ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}"
                }
            }
        }
        stage('Pulling docker image') {
            steps {
                script {
                    sh "docker pull ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}"
                }
            }
        }
        stage('delete existing container') {
            steps {
                script {
                    sh "docker rm -f ${DOCKER_CONTAINER_NAME}"
        
                }
            }
        }
        stage('create a container') {
            steps {
                script {
                    sh "docker run --name ${DOCKER_CONTAINER_NAME} -dp 127.0.0.1:3000:3000 ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}"
        
                }
            }
        }
    }
}